title: Dong ZHANG (张冬)
logo: /assets/img/logo.jpg
position: postdoctoral research scientist
affiliation: Department of Computer Science and Engineering
email: dongz (at) ust.hk
google_scholar: https://scholar.google.com/citations?user=Uf9GqRsAAAAJ
cv_link: https://my-pdf-files.yyliu.net/Yaoyao_Liu_Resume.pdf
github_link: https://github.com/yaoyao-liu/
linkedin: https://www.linkedin.com/in/liuyaoyao/
twitter: https://twitter.com/YaoyaoLiu1/